modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/nanite/JustHammers/issues"
license = "GPL3"


[[mods]]
modId = "justhammers"
version = "${version}"
displayName = "Just Hammers"
authors = "ErrorMikey"
description = '''
Add hammers to the game that are able to mine in a 3x3, 3x3x3, 5x5x3 and finally a 5x5x5! They\'re pretty awesome.
'''
displayURL = "https://github.com/nanite/JustHammers"

[[dependencies.justhammers]]
modId = "neoforge"
required = true
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.justhammers]]
modId = "minecraft"
required = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "justhammers.mixins.json"

[[mixins]]
config = "justhammers-common.mixins.json"
